### ISSUE TITLE
训练没有归一化，预测却有归一化，是不是有问题？

### ISSUE THREAD

**Issue by seven-linglx** [bubbliiiing/centernet-pytorch#26]
训练时候加载数据是dataloader.py 222行，是没有对图片做mean和std归一化的，但预测时predict.py -> centernet.py -> util/util.py -> preprocess_input里却对图片做了mean、std归一化，这应该有问题吧？

**Comment by bubbliiiing** [comment]
120行
        image = np.transpose(preprocess_input(image), (2, 0, 1))

**Comment by seven-linglx** [comment]
> 120行 image = np.transpose(preprocess_input(image), (2, 0, 1))

确实，是我没看清。对图片的处理统一放大

**Comment by seven-linglx** [comment]
DONE
