### ISSUE TITLE
map指标

### ISSUE THREAD

**Issue by ChristmasLee** [bubbliiiing/centernet-pytorch#39]
B导，我在使用get_map.py的时候，您的初始设置confidence为0.02，我正常得到map结果，但是我像其他网络一样把confidence修改成为0.001以后就得不到map结果了，这是为什么呢？
还有就是想问一下，在计算voc的map时，confidence都应该设置为很低，所以是不是0.02和0.001的效果相似？谢谢b导

**Comment by ChristmasLee** [comment]
好吧解决了b导，证明是真的慢

**Comment by bubbliiiing** [comment]
可以调高
