### ISSUE TITLE
修改input_shape后，还能使用centernet_resnet50_voc.pth预训练权重吗

### ISSUE THREAD

**Issue by hua-zi** [bubbliiiing/centernet-pytorch#52]
B导，我把 `input_shape` 修改为 [1536, 1536] , 还能使用您提供的 `centernet_resnet50_voc.pth` 预训练权重吗。我修改之后 `mAP` 从 0.25 左右掉到 0.1以下了 😭

**Comment by bubbliiiing** [comment]
太大了，负样本太多了

**Comment by hua-zi** [comment]
收到！十分感谢B导解惑🌹  请问是不是CenterNet的 ` input_shape ` 最好是使用 [512, 512] 呀？ 是因为网络深度固定，如果resize的尺寸太大，靠后层的卷积核的感受野对图像的覆盖率较小，降低了模型精度吗？

**Comment by bubbliiiing** [comment]
1、不一定呀，512只是原来的设定，但是训练的时候 centernet的正样本太少了
2、有这一部分因素

**Comment by hua-zi** [comment]
好的，谢谢 B导 解答❤
